import type { ProcessedNode } from '../operators/chain';

export function generateClash(nodes: ProcessedNode[], profileName: string = 'Subconverter'): string {
  const lines: string[] = [];
  const groups = new Map<string, ProcessedNode[]>();
  
  // Group nodes
  for (const node of nodes) {
    const key = node.region || node.protocol || 'Default';
    if (!groups.has(key)) groups.set(key, []);
    groups.get(key)!.push(node);
  }
  
  // Header
  lines.push(`# Clash Config - ${profileName}`);
  lines.push('# Generated by Subconverter');
  lines.push('');
  lines.push('mixed-port: 7890');
  lines.push('allow-lan: false');
  lines.push('bind-address: "*"');
  lines.push('mode: rule');
  lines.push('log-level: info');
  lines.push('external-controller: "127.0.0.1:9090"');
  lines.push('');
  
  // DNS
  lines.push('dns:');
  lines.push('  enable: true');
  lines.push('  listen: 0.0.0.0:53');
  lines.push('  enhanced-mode: fake-ip');
  lines.push('  fake-ip-range: 198.18.0.1/16');
  lines.push('  nameserver:');
  lines.push('    - 223.5.5.5');
  lines.push('    - 119.29.29.29');
  lines.push('  fallback:');
  lines.push('    - 8.8.8.8');
  lines.push('    - 1.1.1.1');
  lines.push('');
  
  // Proxies
  lines.push('proxies:');
  for (const node of nodes) {
    const config = typeof node.config === 'string' ? JSON.parse(node.config) : node.config;
    
    switch (node.protocol) {
      case 'ss':
      case 'ss2022':
        lines.push(`  - name: "${node.name}"`);
        lines.push(`    type: ss`);
        lines.push(`    server: "${node.address}"`);
        lines.push(`    port: ${node.port}`);
        lines.push(`    cipher: ${config.method || 'aes-256-gcm'}`);
        lines.push(`    password: "${node.password}"`);
        if (config.plugin) {
          lines.push(`    plugin: "${config.plugin}"`);
          lines.push(`    plugin-opts:`);
          lines.push(`      mode: "${config['plugin-opts']?.mode || 'websocket'}"`);
          lines.push(`      host: "${config['plugin-opts']?.host || ''}"`);
        }
        break;
        
      case 'vmess':
        lines.push(`  - name: "${node.name}"`);
        lines.push(`    type: vmess`);
        lines.push(`    server: "${node.address}"`);
        lines.push(`    port: ${node.port}`);
        lines.push(`    uuid: "${node.uuid}"`);
        lines.push(`    alterId: ${config.aid || 0}`);
        lines.push(`    cipher: ${config.scy || 'auto'}`);
        if (node.network === 'ws') {
          lines.push(`    network: ws`);
          lines.push(`    ws-opts:`);
          lines.push(`      path: "${node.path || '/'}"`);
          lines.push(`      headers:`);
          lines.push(`        Host: "${node.host || ''}"`);
        }
        if (node.network === 'grpc') {
          lines.push(`    network: grpc`);
          lines.push(`    grpc-opts:`);
          lines.push(`      grpc-service-name: "${node.path || ''}"`);
        }
        if (node.tls) {
          lines.push(`    tls: true`);
          if (node.sni) lines.push(`    servername: "${node.sni}"`);
        }
        break;
        
      case 'vless':
        lines.push(`  - name: "${node.name}"`);
        lines.push(`    type: vless`);
        lines.push(`    server: "${node.address}"`);
        lines.push(`    port: ${node.port}`);
        lines.push(`    uuid: "${node.uuid}"`);
        if (config.flow) lines.push(`    flow: "${config.flow}"`);
        if (node.network === 'ws') {
          lines.push(`    network: ws`);
          lines.push(`    ws-opts:`);
          lines.push(`      path: "${node.path || '/'}"`);
        }
        if (node.tls) {
          lines.push(`    tls: true`);
          if (node.sni) lines.push(`    servername: "${node.sni}"`);
        }
        break;
        
      case 'trojan':
        lines.push(`  - name: "${node.name}"`);
        lines.push(`    type: trojan`);
        lines.push(`    server: "${node.address}"`);
        lines.push(`    port: ${node.port}`);
        lines.push(`    password: "${node.password}"`);
        if (node.sni) lines.push(`    sni: "${node.sni}"`);
        if (node.network === 'ws') {
          lines.push(`    network: ws`);
          lines.push(`    ws-opts:`);
          lines.push(`      path: "${node.path || '/'}"`);
        }
        break;
        
      case 'hysteria2':
        lines.push(`  - name: "${node.name}"`);
        lines.push(`    type: hysteria2`);
        lines.push(`    server: "${node.address}"`);
        lines.push(`    port: ${node.port}`);
        lines.push(`    password: "${node.password}"`);
        if (node.sni) lines.push(`    sni: "${node.sni}"`);
        if (node.alpn) lines.push(`    alpn: [${node.alpn.split(',').map(a => `"${a.trim()}"`).join(', ')}]`);
        if (config.insecure === '1') lines.push(`    skip-cert-verify: true`);
        break;
        
      case 'tuic':
        lines.push(`  - name: "${node.name}"`);
        lines.push(`    type: tuic`);
        lines.push(`    server: "${node.address}"`);
        lines.push(`    port: ${node.port}`);
        lines.push(`    uuid: "${node.uuid}"`);
        lines.push(`    password: "${node.password}"`);
        if (node.sni) lines.push(`    sni: "${node.sni}"`);
        if (node.alpn) lines.push(`    alpn: [${node.alpn.split(',').map(a => `"${a.trim()}"`).join(', ')}]`);
        break;
        
      case 'http':
        lines.push(`  - name: "${node.name}"`);
        lines.push(`    type: http`);
        lines.push(`    server: "${node.address}"`);
        lines.push(`    port: ${node.port}`);
        if (config.username) {
          lines.push(`    username: "${config.username}"`);
          lines.push(`    password: "${config.password}"`);
        }
        if (config.tls || node.tls) lines.push(`    tls: true`);
        break;
        
      case 'socks5':
        lines.push(`  - name: "${node.name}"`);
        lines.push(`    type: socks5`);
        lines.push(`    server: "${node.address}"`);
        lines.push(`    port: ${node.port}`);
        if (config.username) {
          lines.push(`    username: "${config.username}"`);
          lines.push(`    password: "${config.password}"`);
        }
        if (config.tls || node.tls) lines.push(`    tls: true`);
        break;
        
      default:
        lines.push(`  - name: "${node.name}"`);
        lines.push(`    type: ${node.protocol}`);
        lines.push(`    server: "${node.address}"`);
        lines.push(`    port: ${node.port}`);
    }
    lines.push('');
  }
  
  // Proxy groups
  const groupNames = Array.from(groups.keys());
  lines.push('proxy-groups:');
  lines.push('  - name: 🔰 Default');
  lines.push('    type: select');
  lines.push('    proxies:');
  for (const g of groupNames) {
    lines.push(`      - "📌 ${g}"`);
  }
  
  // Region groups
  for (const [group, groupNodes] of groups) {
    lines.push('');
    lines.push(`  - name: 📌 ${group}`);
    lines.push('    type: url-test');
    lines.push('    url: "http://www.gstatic.com/generate_204"');
    lines.push('    interval: 300');
    lines.push('    tolerance: 50');
    lines.push('    proxies:');
    for (const n of groupNodes) {
      lines.push(`      - "${n.name}"`);
    }
  }
  
  // Rules (ACL4SSR style)
  lines.push('');
  lines.push('rules:');
  lines.push('  - DOMAIN-SUFFIX,local,DIRECT');
  lines.push('  - IP-CIDR,127.0.0.0/8,DIRECT');
  lines.push('  - IP-CIDR,10.0.0.0/8,DIRECT');
  lines.push('  - IP-CIDR,172.16.0.0/12,DIRECT');
  lines.push('  - IP-CIDR,192.168.0.0/16,DIRECT');
  lines.push('  - IP-CIDR,100.64.0.0/10,DIRECT');
  lines.push('  - IP-CIDR,17.0.0.0/8,DIRECT');
  lines.push('  - GEOIP,CN,DIRECT');
  lines.push('  - DOMAIN-KEYWORD,akadns,DIRECT');
  lines.push('  - MATCH,🔰 Default');
  
  return lines.join('\n');
}
