import type { ProcessedNode } from '../operators/chain';

export function generateLoon(nodes: ProcessedNode[], profileName: string = 'Subconverter'): string {
  const lines: string[] = [];
  
  lines.push(`# Loon Config - ${profileName}`);
  lines.push('# Generated by Subconverter');
  lines.push('');
  
  // Proxy definitions
  lines.push('[Proxy]');
  
  for (const node of nodes) {
    const config = typeof node.config === 'string' ? JSON.parse(node.config) : node.config;
    
    switch (node.protocol) {
      case 'ss':
      case 'ss2022':
        lines.push(`${node.name} = Shadowsocks, ${node.address}, ${node.port}, ${config.method || 'aes-256-gcm'}, "${node.password}"`);
        break;
        
      case 'vmess':
        let vmessRow = `${node.name} = VMess, ${node.address}, ${node.port}, chacha20-poly1305, "${node.uuid}"`;
        if (node.network === 'ws') {
          vmessRow += `, ws=true, ws-path=${node.path || '/'}`;
          if (node.host) vmessRow += `, ws-host=${node.host}`;
        }
        if (node.tls) {
          vmessRow += `, tls=true`;
          if (node.sni) vmessRow += `, tls-host=${node.sni}`;
        }
        lines.push(vmessRow);
        break;
        
      case 'vless':
        let vlessRow = `${node.name} = VLESS, ${node.address}, ${node.port}, "${node.uuid}"`;
        if (node.network === 'ws') {
          vlessRow += `, ws=true, ws-path=${node.path || '/'}`;
          if (node.host) vlessRow += `, ws-host=${node.host}`;
        }
        if (node.tls) {
          vlessRow += `, tls=true`;
          if (node.sni) vlessRow += `, tls-host=${node.sni}`;
        }
        lines.push(vlessRow);
        break;
        
      case 'trojan':
        let trojanRow = `${node.name} = Trojan, ${node.address}, ${node.port}, "${node.password}"`;
        if (node.tls) {
          trojanRow += `, tls=true`;
          if (node.sni) trojanRow += `, tls-host=${node.sni}`;
        }
        if (node.network === 'ws') {
          trojanRow += `, ws=true, ws-path=${node.path || '/'}`;
          if (node.host) trojanRow += `, ws-host=${node.host}`;
        }
        lines.push(trojanRow);
        break;
        
      case 'hysteria2':
        lines.push(`${node.name} = Hysteria2, ${node.address}, ${node.port}, "${node.password}"${node.sni ? `, sni=${node.sni}` : ''}`);
        break;
        
      case 'http':
        let httpRow = `${node.name} = HTTP, ${node.address}, ${node.port}`;
        if (config.username) httpRow += `, ${config.username}, ${config.password}`;
        if (config.tls || node.tls) httpRow += `, tls=true`;
        lines.push(httpRow);
        break;
        
      case 'socks5':
        let socksRow = `${node.name} = SOCKS5, ${node.address}, ${node.port}`;
        if (config.username) socksRow += `, ${config.username}, ${config.password}`;
        lines.push(socksRow);
        break;
        
      default:
        lines.push(`# ${node.protocol} - ${node.name}`);
    }
  }
  
  // Proxy groups
  lines.push('');
  lines.push('[Proxy Group]');
  const allNames = nodes.map(n => n.name);
  lines.push(`Select = select, ${allNames.join(', ')}`);
  
  // Auto groups by region
  const regionMap = new Map<string, string[]>();
  for (const node of nodes) {
    const region = node.region || node.protocol;
    if (!regionMap.has(region)) regionMap.set(region, []);
    regionMap.get(region)!.push(node.name);
  }
  
  for (const [region, names] of regionMap) {
    lines.push(`🌍 ${region} = url-test, ${names.join(', ')}, url=http://www.gstatic.com/generate_204, interval=300, tolerance=50`);
  }
  
  // Rules
  lines.push('');
  lines.push('[Rule]');
  lines.push('DOMAIN-SUFFIX,local,DIRECT');
  lines.push('IP-CIDR,127.0.0.0/8,DIRECT');
  lines.push('IP-CIDR,10.0.0.0/8,DIRECT');
  lines.push('IP-CIDR,172.16.0.0/12,DIRECT');
  lines.push('IP-CIDR,192.168.0.0/16,DIRECT');
  lines.push('GEOIP,CN,DIRECT');
  lines.push('FINAL,Select');
  
  return lines.join('\n');
}
