import type { ProcessedNode } from '../operators/chain';

export function generateQuantumultX(nodes: ProcessedNode[], profileName: string = 'Subconverter'): string {
  const lines: string[] = [];
  
  lines.push(`# Quantumult X Config - ${profileName}`);
  lines.push('# Generated by Subconverter');
  lines.push('');
  lines.push('[general]');
  lines.push('excluded_routes = 192.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12, 100.64.0.0/10, 127.0.0.1');
  lines.push('dns_exclusion_list = *.cmcm.com, *.umeng.com, *.oupeng.com');
  lines.push('');
  
  // Server definitions
  lines.push('[server]');
  
  for (const node of nodes) {
    const config = typeof node.config === 'string' ? JSON.parse(node.config) : node.config;
    const tag = node.name;
    
    switch (node.protocol) {
      case 'ss':
      case 'ss2022':
        lines.push(`shadowsocks=${node.address}:${node.port}, method=${config.method || 'aes-256-gcm'}, password=${node.password}, tag=${tag}`);
        break;
        
      case 'vmess':
        let vmessStr = `vmess=${node.address}:${node.port}, method=chacha20-poly1305, password=${node.uuid}, tag=${tag}`;
        if (node.tls) vmessStr += `, obfs=over-tls`;
        if (node.network === 'ws') {
          vmessStr += `, obfs=ws, obfs-uri=${node.path || '/'}`;
          if (node.host) vmessStr += `, obfs-host=${node.host}`;
        }
        lines.push(vmessStr);
        break;
        
      case 'trojan':
        let trojanStr = `trojan=${node.address}:${node.port}, password=${node.password}, tag=${tag}`;
        if (node.sni) trojanStr += `, tls-host=${node.sni}`;
        trojanStr += `, tls-verification=true`;
        if (node.network === 'ws') {
          trojanStr += `, obfs=ws, obfs-uri=${node.path || '/'}`;
          if (node.host) trojanStr += `, obfs-host=${node.host}`;
        }
        lines.push(trojanStr);
        break;
        
      case 'http':
        let httpStr = `http=${node.address}:${node.port}`;
        if (config.username) httpStr += `, username=${config.username}, password=${config.password}`;
        httpStr += `, tag=${tag}`;
        if (config.tls || node.tls) httpStr += `, over-tls=true`;
        lines.push(httpStr);
        break;
        
      case 'socks5':
        let socksStr = `socks5=${node.address}:${node.port}`;
        if (config.username) socksStr += `, username=${config.username}, password=${config.password}`;
        socksStr += `, tag=${tag}`;
        lines.push(socksStr);
        break;
        
      default:
        lines.push(`# Unsupported: ${node.protocol} - ${tag}`);
    }
  }
  
  // Policy groups
  lines.push('');
  lines.push('[policy]');
  const allTags = nodes.map(n => n.name);
  lines.push(`static=🔰 Select, proxy, ${allTags.join(', ')}`);
  
  // Region groups
  const regionMap = new Map<string, string[]>();
  for (const node of nodes) {
    const region = node.region || node.protocol;
    if (!regionMap.has(region)) regionMap.set(region, []);
    regionMap.get(region)!.push(node.name);
  }
  
  for (const [region, tags] of regionMap) {
    lines.push(`available=🌍 ${region}, ${tags.join(', ')}`);
  }
  
  // Filter rules
  lines.push('');
  lines.push('[filter_local]');
  lines.push('host-suffix, local, direct');
  lines.push('ip-cidr, 127.0.0.0/8, direct');
  lines.push('ip-cidr, 10.0.0.0/8, direct');
  lines.push('ip-cidr, 172.16.0.0/12, direct');
  lines.push('ip-cidr, 192.168.0.0/16, direct');
  lines.push('ip-cidr, 100.64.0.0/10, direct');
  lines.push('geoip, cn, direct');
  lines.push('final, 🔰 Select');
  
  return lines.join('\n');
}
