import type { ProcessedNode } from '../operators/chain';

export function generateShadowrocket(nodes: ProcessedNode[], profileName: string = 'Subconverter'): string {
  const lines: string[] = [];
  
  lines.push(`# Shadowrocket Config - ${profileName}`);
  lines.push('# Generated by Subconverter');
  lines.push('');
  lines.push('[General]');
  lines.push('bypass-system = true');
  lines.push('skip-proxy = 192.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12, localhost, *.local, ::ffff:0:0:0:0/1, ::ffff:128:0:0:0/1');
  lines.push('');
  
  // Generate each node as Shadowrocket format
  for (const node of nodes) {
    const config = typeof node.config === 'string' ? JSON.parse(node.config) : node.config;
    
    switch (node.protocol) {
      case 'ss':
      case 'ss2022':
        const ssMethod = config.method || 'aes-256-gcm';
        const ssEncoded = btoa(`${ssMethod}:${node.password}@${node.address}:${node.port}`);
        lines.push(`ss://${ssEncoded}#${encodeURIComponent(node.name)}`);
        break;
        
      case 'vmess':
        const vmessCfg: any = {
          v: '2',
          ps: node.name,
          add: node.address,
          port: node.port,
          id: node.uuid,
          aid: config.aid || 0,
          scy: config.scy || 'auto',
          net: node.network || 'tcp',
          type: 'none',
          host: node.host || '',
          path: node.path || '',
          tls: node.tls ? 'tls' : '',
          sni: node.sni || '',
        };
        lines.push(`vmess://${btoa(JSON.stringify(vmessCfg))}`);
        break;
        
      case 'vless':
        let vlessUri = `vless://${node.uuid}@${node.address}:${node.port}`;
        const vlessParams: string[] = [];
        if (config.encryption) vlessParams.push(`encryption=${config.encryption}`);
        if (config.flow) vlessParams.push(`flow=${config.flow}`);
        if (config.security) vlessParams.push(`security=${config.security}`);
        if (node.sni) vlessParams.push(`sni=${node.sni}`);
        if (node.alpn) vlessParams.push(`alpn=${node.alpn}`);
        if (node.fingerprint) vlessParams.push(`fp=${node.fingerprint}`);
        if (node.path) vlessParams.push(`path=${node.path}`);
        if (node.host) vlessParams.push(`host=${node.host}`);
        if (config.type) vlessParams.push(`type=${config.type}`);
        if (vlessParams.length > 0) vlessUri += `?${vlessParams.join('&')}`;
        vlessUri += `#${encodeURIComponent(node.name)}`;
        lines.push(vlessUri);
        break;
        
      case 'trojan':
        let trojanUri = `trojan://${node.password}@${node.address}:${node.port}`;
        const trojanParams: string[] = [];
        if (node.sni) trojanParams.push(`sni=${node.sni}`);
        if (node.alpn) trojanParams.push(`alpn=${node.alpn}`);
        if (node.fingerprint) trojanParams.push(`fp=${node.fingerprint}`);
        if (node.path) trojanParams.push(`path=${node.path}`);
        if (node.host) trojanParams.push(`host=${node.host}`);
        if (config.type && config.type !== 'tcp') trojanParams.push(`type=${config.type}`);
        if (trojanParams.length > 0) trojanUri += `?${trojanParams.join('&')}`;
        trojanUri += `#${encodeURIComponent(node.name)}`;
        lines.push(trojanUri);
        break;
        
      case 'hysteria2':
        let hyUri = `hysteria2://${node.password}@${node.address}:${node.port}`;
        const hyParams: string[] = [];
        if (node.sni) hyParams.push(`sni=${node.sni}`);
        if (node.alpn) hyParams.push(`alpn=${node.alpn}`);
        if (config.insecure === '1') hyParams.push(`insecure=1`);
        if (config.obfs) hyParams.push(`obfs=${config.obfs}`);
        if (config['obfs-password']) hyParams.push(`obfs-password=${config['obfs-password']}`);
        if (hyParams.length > 0) hyUri += `?${hyParams.join('&')}`;
        hyUri += `#${encodeURIComponent(node.name)}`;
        lines.push(hyUri);
        break;
        
      case 'tuic':
        let tuicPass = node.password ? `:${node.password}` : '';
        let tuicUri = `tuic://${node.uuid}${tuicPass}@${node.address}:${node.port}`;
        const tuicParams: string[] = [];
        if (config.congestion_control) tuicParams.push(`congestion_control=${config.congestion_control}`);
        if (node.sni) tuicParams.push(`sni=${node.sni}`);
        if (node.alpn) tuicParams.push(`alpn=${node.alpn}`);
        if (tuicParams.length > 0) tuicUri += `?${tuicParams.join('&')}`;
        tuicUri += `#${encodeURIComponent(node.name)}`;
        lines.push(tuicUri);
        break;
        
      case 'snell':
        let snellUri = `snell://${node.password}@${node.address}:${node.port}`;
        const snellParams: string[] = [];
        if (config.version) snellParams.push(`version=${config.version}`);
        if (config.obfs) snellParams.push(`obfs=${config.obfs}`);
        if (config['obfs-host']) snellParams.push(`obfs-host=${config['obfs-host']}`);
        if (snellParams.length > 0) snellUri += `?${snellParams.join('&')}`;
        snellUri += `#${encodeURIComponent(node.name)}`;
        lines.push(snellUri);
        break;
        
      default:
        lines.push(`# Unsupported: ${node.protocol} - ${node.name}`);
    }
  }
  
  return lines.join('\n');
}
