import type { ProcessedNode } from '../operators/chain';

export function generateSurge(nodes: ProcessedNode[], profileName: string = 'Subconverter'): string {
  const lines: string[] = [];
  
  lines.push(`# Surge Config - ${profileName}`);
  lines.push('# Generated by Subconverter');
  lines.push('');
  lines.push('[General]');
  lines.push('bypass-system = true');
  lines.push('skip-proxy = 127.0.0.1, 192.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12, 100.64.0.0/10, localhost, *.local, ::ffff:0:0:0:0/1, ::ffff:128:0:0:0/1');
  lines.push('bypass-tun = 10.0.0.0/8, 100.64.0.0/10, 127.0.0.1, 192.168.0.0/16');
  lines.push('dns-server = system, 223.5.5.5, 119.29.29.29');
  lines.push('always-real-ip = *.srv.nintendo.net, *.stun.playstation.net, xbox.*.microsoft.com, *.xboxlive.com');
  lines.push('');
  lines.push('[Proxy]');
  
  for (const node of nodes) {
    const config = typeof node.config === 'string' ? JSON.parse(node.config) : node.config;
    
    switch (node.protocol) {
      case 'ss':
      case 'ss2022':
        lines.push(`${node.name} = ss, ${node.address}, ${node.port}, encrypt-method=${config.method || 'aes-256-gcm'}, password=${node.password}`);
        break;
        
      case 'vmess':
        lines.push(`${node.name} = vmess, ${node.address}, ${node.port}, username=${node.uuid}`);
        if (node.network === 'ws') {
          lines.push(`  ws = true, ws-path=${node.path || '/'}`);
        }
        if (node.tls) {
          lines.push(`  tls = true`);
          if (node.sni) lines.push(`  sni = ${node.sni}`);
        }
        break;
        
      case 'trojan':
        lines.push(`${node.name} = trojan, ${node.address}, ${node.port}, password=${node.password}`);
        if (node.sni) lines.push(`  sni = ${node.sni}`);
        break;
        
      case 'http':
        lines.push(`${node.name} = http, ${node.address}, ${node.port}${config.username ? `, username=${config.username}, password=${config.password}` : ''}`);
        if (config.tls || node.tls) lines.push(`  tls = true`);
        break;
        
      case 'socks5':
        lines.push(`${node.name} = socks5, ${node.address}, ${node.port}${config.username ? `, username=${config.username}, password=${config.password}` : ''}`);
        break;
        
      case 'snell':
        lines.push(`${node.name} = snell, ${node.address}, ${node.port}, psk=${node.password}, version=${config.version || 4}`);
        if (config.obfs) lines.push(`  obfs = ${config.obfs}, obfs-host=${config['obfs-host'] || ''}`);
        break;
        
      default:
        lines.push(`${node.name} = ${node.protocol}, ${node.address}, ${node.port}`);
    }
  }
  
  // Proxy groups
  lines.push('');
  lines.push('[Proxy Group]');
  const regionMap = new Map<string, string[]>();
  for (const node of nodes) {
    const region = node.region || node.protocol;
    if (!regionMap.has(region)) regionMap.set(region, []);
    regionMap.get(region)!.push(node.name);
  }
  
  const allNames = nodes.map(n => n.name);
  lines.push(`Select = select, ${allNames.join(', ')}`);
  
  for (const [region, names] of regionMap) {
    lines.push(`🌍 ${region} = url-test, ${names.join(', ')}, url=http://www.gstatic.com/generate_204, interval=300`);
  }
  
  // Rules
  lines.push('');
  lines.push('[Rule]');
  lines.push('DOMAIN-SUFFIX,local,DIRECT');
  lines.push('IP-CIDR,127.0.0.0/8,DIRECT');
  lines.push('IP-CIDR,10.0.0.0/8,DIRECT');
  lines.push('IP-CIDR,172.16.0.0/12,DIRECT');
  lines.push('IP-CIDR,192.168.0.0/16,DIRECT');
  lines.push('GEOIP,CN,DIRECT');
  lines.push('FINAL,Select');
  
  return lines.join('\n');
}
