import type { ProcessedNode } from '../operators/chain';

export function generateV2Ray(nodes: ProcessedNode[], profileName: string = 'Subconverter'): string {
  const lines: string[] = [];
  
  lines.push(`# V2Ray Config - ${profileName}`);
  lines.push('# Generated by Subconverter');
  lines.push('#');
  lines.push('# To use in V2RayN/V2RayNG:');
  lines.push('#   1. Copy each line below');
  lines.push('#   2. In V2RayN: Servers -> Import bulk URL from clipboard');
  lines.push('#   3. In V2RayNG: + -> Import from clipboard');
  lines.push('');
  
  for (const node of nodes) {
    const config = typeof node.config === 'string' ? JSON.parse(node.config) : node.config;
    
    switch (node.protocol) {
      case 'ss':
      case 'ss2022':
        const ssMethod = config.method || 'aes-256-gcm';
        const ssEncoded = btoa(`${ssMethod}:${node.password}@${node.address}:${node.port}`);
        lines.push(`ss://${ssEncoded}#${encodeURIComponent(node.name)}`);
        break;
        
      case 'vmess':
        const vmessCfg: any = {
          v: '2',
          ps: node.name,
          add: node.address,
          port: node.port,
          id: node.uuid,
          aid: config.aid || 0,
          scy: config.scy || 'auto',
          net: node.network || 'tcp',
          type: 'none',
          host: node.host || '',
          path: node.path || '',
          tls: node.tls ? 'tls' : '',
          sni: node.sni || '',
          alpn: node.alpn || '',
          fp: node.fingerprint || '',
        };
        lines.push(`vmess://${btoa(JSON.stringify(vmessCfg))}`);
        break;
        
      case 'vless':
        let vlessUri = `vless://${node.uuid}@${node.address}:${node.port}`;
        const vlessParams: string[] = [];
        if (config.encryption) vlessParams.push(`encryption=${config.encryption}`);
        if (config.security) vlessParams.push(`security=${config.security}`);
        if (config.flow) vlessParams.push(`flow=${config.flow}`);
        if (node.sni) vlessParams.push(`sni=${node.sni}`);
        if (node.alpn) vlessParams.push(`alpn=${node.alpn}`);
        if (node.fingerprint) vlessParams.push(`fp=${node.fingerprint}`);
        if (node.path && config.type === 'ws') vlessParams.push(`path=${node.path}`);
        if (node.host && config.type === 'ws') vlessParams.push(`host=${node.host}`);
        if (config.type) vlessParams.push(`type=${config.type}`);
        if (config.pbk) vlessParams.push(`pbk=${config.pbk}`);
        if (config.sid) vlessParams.push(`sid=${config.sid}`);
        if (vlessParams.length > 0) vlessUri += `?${vlessParams.join('&')}`;
        vlessUri += `#${encodeURIComponent(node.name)}`;
        lines.push(vlessUri);
        break;
        
      case 'trojan':
        let trojanUri = `trojan://${encodeURIComponent(node.password)}@${node.address}:${node.port}`;
        const trojanParams: string[] = [];
        if (node.sni) trojanParams.push(`sni=${node.sni}`);
        if (node.alpn) trojanParams.push(`alpn=${node.alpn}`);
        if (node.fingerprint) trojanParams.push(`fp=${node.fingerprint}`);
        if (node.path && config.type === 'ws') trojanParams.push(`path=${node.path}`);
        if (node.host && config.type === 'ws') trojanParams.push(`host=${node.host}`);
        if (config.type && config.type !== 'tcp') trojanParams.push(`type=${config.type}`);
        if (trojanParams.length > 0) trojanUri += `?${trojanParams.join('&')}`;
        trojanUri += `#${encodeURIComponent(node.name)}`;
        lines.push(trojanUri);
        break;
        
      case 'hysteria2':
        let hyUri = `hysteria2://${node.password}@${node.address}:${node.port}`;
        const hyParams: string[] = [];
        if (node.sni) hyParams.push(`sni=${node.sni}`);
        if (node.alpn) hyParams.push(`alpn=${node.alpn}`);
        if (config.insecure === '1') hyParams.push(`insecure=1`);
        if (config.obfs) hyParams.push(`obfs=${config.obfs}`);
        if (hyParams.length > 0) hyUri += `?${hyParams.join('&')}`;
        hyUri += `#${encodeURIComponent(node.name)}`;
        lines.push(hyUri);
        break;
        
      default:
        lines.push(`# Unsupported: ${node.protocol} - ${node.name}`);
    }
  }
  
  return lines.join('\n');
}
